// CALCULATIONS layer for the Precision Stop game. Pure functions only — no
// rAF, no DOM, no React. The component runs the clock and paints; every rule
// about where the marker is and what a stop is worth lives here.
//
// THIS FILE IS ONE HALF OF A PAIR. The other is
// backend/internal/game/precision.go, and the two must agree exactly, because
// the server replays the sweep from the stop time and its answer is the one that
// counts. A divergence does not show up as a wrong number in a log — it shows up
// as a player freezing the marker dead centre and being told they were eleven
// off. That is why:
//
//   - EVERY position is an integer, and every division truncates toward zero.
//     `Math.floor` on a non-negative quotient is what Go's `/` does on ints, and
//     the arithmetic here is arranged so no quotient is ever negative. Floating
//     point would drift; integers cannot.
//   - The marker's starting PHASE is not drawn here. It arrives in the round's
//     challenge, because a phase the client picked is a phase the server cannot
//     score against — which is exactly the hole this game used to have.
//
// The tests in precision.test.ts read a fixture generated by the Go side, so a
// change to one half that the other did not follow fails a build rather than a
// player.

import type { MessageKey } from "../i18n";

/**
 * Half the track's virtual width, and therefore the worst possible score:
 * stopping at either end is this far off centre.
 *
 * Virtual units, not pixels. The track renders at whatever width the screen
 * allows, but positions are always expressed against this fixed scale, so a
 * phone and a kiosk produce comparable scores.
 *
 * Mirrors game.PrecisionTrackHalf, and deliberately NOT part of the challenge:
 * this is the SCORING SCALE, which every award's threshold for this game is
 * written in, so it is a shared constant rather than something a round can
 * arrive carrying. Tuning travels; the unit does not.
 */
export const TRACK_HALF = 100;

/** The full sweep, end to end. Centre is at TRACK_HALF. */
export const TRACK_WIDTH = TRACK_HALF * 2;

/** The score for a player who never stops the marker: the worst legal one. */
export const WORST_SCORE = TRACK_HALF;

/**
 * How far off centre still fills the reveal meter, mirroring the game's
 * TargetScore, and how far still wins something at all. Both are drawn on the
 * track so the player can see what they are aiming at instead of discovering
 * the thresholds on the result screen.
 */
export const BULLSEYE_OFF = 5;
export const NEAR_OFF = 25;

/**
 * One full there-and-back sweep, in ms.
 *
 * A FALLBACK, not the source of truth: a live round is driven by the period the
 * server issued with the session. It exists so the game is playable — and
 * testable — without a server having spoken, and it is the value the golden
 * fixture was generated against. Mirrors game.PrecisionSweepPeriodMs.
 */
export const SWEEP_PERIOD_MS = 1400;

/**
 * How long the track holds after a stop, before the round hands off.
 *
 * Without it the screen changes on the same pointer event that ends the round,
 * so the one thing the player was aiming at — where the marker actually
 * stopped — is never shown. The score reveal that follows says how far off they
 * were as a number; only the track can say it as a *place*, and it is gone by
 * then.
 *
 * Deliberately NOT routed through pacing.holdMs, which collapses every beat to
 * zero under reduced motion. That rule is right for the celebration and the
 * reveal, which are motion; this beat is a readout that happens to be
 * animated. The ring drawn on it is decoration and the global reduce-motion
 * rule in index.css already neutralises that, leaving the frozen marker and the
 * verdict — which is exactly what a player who asked for less movement should
 * still get.
 *
 * Short on purpose: the celebration is 1600ms away and the reveal 2200ms behind
 * that, so this is paying into an ending that is already long.
 */
export const STOP_HOLD_MS = 700;

/** The numbers a Precision Stop round is played by. Mirrors
 *  game.PrecisionChallenge. */
export interface PrecisionSweep {
  /** Where in the sweep the marker starts, in ms. Drawn by the SERVER. */
  phaseMs: number;
  /** One full there-and-back sweep, in ms. */
  periodMs: number;
}

function isPositiveInt(v: unknown): v is number {
  return typeof v === "number" && Number.isFinite(v) && v > 0;
}

/**
 * Narrows the server's challenge into the sweep a round is played by, or returns
 * null when it cannot be read.
 *
 * NULL RATHER THAN A FALLBACK, and this is the one place this game deliberately
 * differs from `stackPhysics`. Stack's challenge is a block of constants, so
 * substituting a built-in is harmless — the numbers are the same ones. This
 * game's challenge carries the PHASE, and the phase is the only thing the server
 * will score against. Playing a round at a phase of 0 because the real one was
 * unreadable produces a marker that visibly stops dead centre and a result screen
 * that says otherwise, which is worse than refusing to start: the player is shown
 * a number with no relationship to what they watched.
 *
 * A missing challenge and a malformed one therefore both fail here, and the
 * component's job is to say so rather than to play a different game. The server
 * makes the same distinction in reverse — see precisionChallengeOf, which rejects
 * for the same reason.
 */
export function precisionSweep(challenge: unknown): PrecisionSweep | null {
  if (typeof challenge !== "object" || challenge === null) return null;
  const c = challenge as Record<string, unknown>;
  if (!isPositiveInt(c.periodMs)) return null;
  const periodMs = Math.floor(c.periodMs);
  // A phase of exactly 0 is legal, so this cannot use isPositiveInt.
  if (typeof c.phaseMs !== "number" || !Number.isFinite(c.phaseMs)) return null;
  const phaseMs = Math.floor(c.phaseMs);
  // Out of range rather than wrapped: a challenge this build did not write is one
  // it should not pretend to understand. The server applies the same bound.
  if (phaseMs < 0 || phaseMs >= periodMs) return null;
  return { phaseMs, periodMs };
}

/**
 * Where the marker is `elapsedMs` into a round that began at `phaseMs` of its
 * sweep, as an integer position in 0…TRACK_WIDTH.
 *
 * A triangle wave: the marker runs to one end, turns, and comes back at the
 * same speed, because an eased turn would make the ends easier to hit than the
 * middle and this game is only interesting if the middle is the hard part.
 *
 * `phaseMs` is in MILLISECONDS and comes from the server's challenge — it used
 * to be a 0–1 fraction drawn by the component with `Math.random()`, which is
 * precisely why this game's score could not be checked. Mirrors
 * game.PrecisionSweepPosition; integer arithmetic throughout, truncating exactly
 * where Go does — see this file's header for why that is not a detail.
 */
export function sweepPosition(elapsedMs: number, phaseMs: number, periodMs = SWEEP_PERIOD_MS): number {
  const period = isPositiveInt(periodMs) ? Math.floor(periodMs) : SWEEP_PERIOD_MS;
  const elapsed = Number.isFinite(elapsedMs) && elapsedMs > 0 ? Math.floor(elapsedMs) : 0;
  const phase = Number.isFinite(phaseMs) && phaseMs > 0 ? Math.floor(phaseMs) : 0;

  const half = Math.floor(period / 2);
  // A period too short to have two halves has no sweep to speak of; the centre
  // is the only answer that is not a lie about where the marker was.
  if (half <= 0) return TRACK_HALF;

  const t = (elapsed + phase) % period;
  let pos =
    t < half
      ? Math.floor((t * TRACK_WIDTH) / half)
      : TRACK_WIDTH - Math.floor(((t - half) * TRACK_WIDTH) / half);
  if (pos < 0) pos = 0;
  if (pos > TRACK_WIDTH) pos = TRACK_WIDTH;
  return pos;
}

/**
 * The score for stopping at `position`: the distance from centre.
 *
 * Zero is a legal, and indeed the intended, result. Every other game in the
 * catalog has a score that cannot reach zero, which is precisely the assumption
 * this game exists to break — see benchmarkFor in ../reveal/calc.
 *
 * The component uses this to SHOW the player where they landed during the hold.
 * It is not what gets submitted: the round reports the stop time and the server's
 * own copy of this function decides the score. Mirrors
 * game.PrecisionMissDistance, which is the one that counts.
 */
export function missDistance(position: number): number {
  if (!Number.isFinite(position)) return WORST_SCORE;
  const off = Math.abs(Math.floor(position) - TRACK_HALF);
  return Math.max(0, Math.min(WORST_SCORE, off));
}

/**
 * Replays a round exactly as the server will, for tests and for a component that
 * wants to show a distance before the result lands.
 *
 * Mirrors game.ScorePrecisionStop, including which malformations mean what: an
 * EMPTY stop list is a timeout and scores the worst legal distance, more than one
 * stop could not have happened, and a stop outside the round did not either.
 * Returns null for a round the server would reject — including one with no
 * readable sweep, because there is nothing to replay against.
 */
export function scorePrecisionStop(
  stops: number[],
  durationMs: number,
  sweep: PrecisionSweep | null,
): number | null {
  if (!(durationMs > 0)) return null;
  if (stops.length === 0) return WORST_SCORE;
  if (stops.length > 1) return null;
  if (!sweep) return null;
  const stop = stops[0];
  if (!Number.isInteger(stop) || stop < 0 || stop > durationMs) return null;
  return missDistance(sweepPosition(stop, sweep.phaseMs, sweep.periodMs));
}

/** A position as a 0–100 percentage across the track, for placing it visually. */
export function trackPercent(position: number): number {
  if (!Number.isFinite(position)) return 50;
  const pct = (position / TRACK_WIDTH) * 100;
  return Math.max(0, Math.min(100, pct));
}

/** How wide a "within `off` of centre" band is, as a percentage of the track. */
export function zoneWidthPercent(off: number): number {
  const safe = Number.isFinite(off) ? Math.max(0, off) : 0;
  return Math.min(100, ((safe * 2) / TRACK_WIDTH) * 100);
}

/**
 * Rating shown the moment a stop lands, for immediate feedback.
 *
 * Returns a message key, not a word: which band a stop falls into is a rule
 * about this game and belongs here, while what that band is CALLED is a
 * translation and belongs in ../i18n. The component looks it up.
 */
export function precisionVerdict(off: number): MessageKey {
  if (off <= 0) return "precision.verdict.perfect";
  if (off <= BULLSEYE_OFF) return "precision.verdict.deadOn";
  if (off <= 12) return "precision.verdict.close";
  if (off <= NEAR_OFF) return "precision.verdict.near";
  return "precision.verdict.wide";
}
