import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { COMPLETE_BEAT_MS } from "../reveal/pacing";
import {
  BULLSEYE_OFF,
  STOP_HOLD_MS,
  SWEEP_PERIOD_MS,
  TRACK_HALF,
  TRACK_WIDTH,
  WORST_SCORE,
  missDistance,
  precisionSweep,
  precisionVerdict,
  scorePrecisionStop,
  sweepPosition,
  trackPercent,
  zoneWidthPercent,
} from "./precision";

/**
 * The fixture is GENERATED BY THE GO IMPLEMENTATION
 * (backend/internal/game/precision_golden_test.go) and committed. Reading it here
 * is what turns "these two simulations should agree" from a comment into a
 * failing build — see the same arrangement in stack.test.ts, and that file's note
 * on why `node:fs` in a package test is not a boundary violation.
 */
const golden = JSON.parse(
  readFileSync(
    fileURLToPath(
      new URL("../../../../../backend/internal/game/testdata/precision_golden.json", import.meta.url),
    ),
    "utf8",
  ),
) as {
  durationMs: number;
  periodMs: number;
  trackHalf: number;
  sweeps: { elapsedMs: number; phaseMs: number; periodMs: number; position: number; off: number }[];
  rounds: { stopMs: number[]; phaseMs: number; score: number }[];
};

describe("the sweep agrees with the server", () => {
  // The headline guarantee. Every case the Go implementation computed must come
  // out identical here — if it does not, a player will one day freeze the marker
  // dead centre and be told they were eleven off.
  it("computes every golden position identically", () => {
    expect(golden.sweeps.length).toBeGreaterThan(0);
    const mismatches = golden.sweeps.filter(
      (c) => sweepPosition(c.elapsedMs, c.phaseMs, c.periodMs) !== c.position,
    );
    expect(mismatches).toEqual([]);
  });

  it("scores every golden position identically", () => {
    const mismatches = golden.sweeps.filter(
      (c) => missDistance(sweepPosition(c.elapsedMs, c.phaseMs, c.periodMs)) !== c.off,
    );
    expect(mismatches).toEqual([]);
  });

  it("scores every golden round identically", () => {
    expect(golden.rounds.length).toBeGreaterThan(0);
    const got = golden.rounds.map((r) =>
      scorePrecisionStop(r.stopMs, golden.durationMs, { phaseMs: r.phaseMs, periodMs: golden.periodMs }),
    );
    expect(got).toEqual(golden.rounds.map((r) => r.score));
  });

  // The fixture is only worth anything while the constants it was generated
  // against are the ones this side falls back to.
  it("falls back to the same constants the fixture was generated with", () => {
    expect(golden.periodMs).toBe(SWEEP_PERIOD_MS);
    expect(golden.trackHalf).toBe(TRACK_HALF);
    expect(golden.durationMs).toBe(6000);
  });
});

describe("sweepPosition", () => {
  it("runs end to end and back within one period", () => {
    expect(sweepPosition(0, 0)).toBe(0);
    expect(sweepPosition(SWEEP_PERIOD_MS / 4, 0)).toBe(TRACK_HALF);
    expect(sweepPosition(SWEEP_PERIOD_MS / 2, 0)).toBe(TRACK_WIDTH);
    expect(sweepPosition((SWEEP_PERIOD_MS * 3) / 4, 0)).toBe(TRACK_HALF);
    // Back to the start, ready to repeat — no jump at the wrap.
    expect(sweepPosition(SWEEP_PERIOD_MS, 0)).toBe(0);
  });

  it("moves at a constant speed, so the middle is no easier than the ends", () => {
    // Equal time slices must cover equal distance on a single leg. An eased
    // turnaround would make the ends slow and the centre a coin flip. Integer
    // truncation means "equal" is within one unit rather than exact.
    const step = SWEEP_PERIOD_MS / 20;
    const a = sweepPosition(step, 0) - sweepPosition(0, 0);
    const b = sweepPosition(step * 5, 0) - sweepPosition(step * 4, 0);
    expect(Math.abs(a - b)).toBeLessThanOrEqual(1);
  });

  it("treats the phase as a head start in milliseconds", () => {
    // A phase of p must put the marker exactly where elapsed p with no phase
    // does; the server relies on that equivalence to replay a round.
    for (const p of [0, 1, 173, 700, 1013, 1399]) {
      expect(sweepPosition(0, p)).toBe(sweepPosition(p, 0));
    }
    expect(sweepPosition(0, SWEEP_PERIOD_MS / 4)).toBe(TRACK_HALF);
    expect(sweepPosition(0, SWEEP_PERIOD_MS / 2)).toBe(TRACK_WIDTH);
  });

  it("returns whole units only, because the server scores in them", () => {
    for (let ms = 0; ms < SWEEP_PERIOD_MS; ms += 13) {
      expect(Number.isInteger(sweepPosition(ms, 371))).toBe(true);
    }
  });

  it("stays on the track for nonsense input", () => {
    for (const [elapsed, phase] of [
      [Number.NaN, 0],
      [-500, 0],
      [1000, Number.NaN],
      [Number.POSITIVE_INFINITY, 300],
    ] as const) {
      const p = sweepPosition(elapsed, phase);
      expect(p).toBeGreaterThanOrEqual(0);
      expect(p).toBeLessThanOrEqual(TRACK_WIDTH);
    }
  });
});

describe("precisionSweep", () => {
  it("accepts the challenge the server actually sends", () => {
    expect(precisionSweep({ phaseMs: 371, periodMs: 1400 })).toEqual({ phaseMs: 371, periodMs: 1400 });
    // A phase of exactly zero is legal — it is one of the values the draw can
    // produce, and rejecting it would break one round in every period.
    expect(precisionSweep({ phaseMs: 0, periodMs: 1400 })).toEqual({ phaseMs: 0, periodMs: 1400 });
  });

  /**
   * The deliberate difference from `stackPhysics`, which falls back per field.
   * This game's challenge carries the PHASE, and the phase is the only thing the
   * server scores against — so a substituted one would show the player a marker
   * stopping somewhere their score does not describe. Refusing is the honest
   * option, and the component renders an error rather than a different game.
   */
  it("refuses anything it cannot score against rather than substituting a default", () => {
    for (const bad of [
      undefined,
      null,
      "1400",
      42,
      {},
      { periodMs: 1400 },
      { phaseMs: 100 },
      { phaseMs: 100, periodMs: 0 },
      { phaseMs: -1, periodMs: 1400 },
      // At or beyond its own period: the server applies the same bound.
      { phaseMs: 1400, periodMs: 1400 },
      { phaseMs: Number.NaN, periodMs: 1400 },
      { phaseMs: 100, periodMs: "1400" },
    ]) {
      expect(precisionSweep(bad)).toBeNull();
    }
  });
});

describe("scorePrecisionStop", () => {
  const sweep = { phaseMs: 0, periodMs: SWEEP_PERIOD_MS };

  it("scores a stop dead centre as zero", () => {
    expect(scorePrecisionStop([SWEEP_PERIOD_MS / 4], 6000, sweep)).toBe(0);
  });

  /**
   * A player who never stops the marker is an ordinary outcome, not a malformed
   * round, and it must not need a sweep to say so — there is nothing to replay.
   */
  it("treats no stop as a timeout worth the worst legal score", () => {
    expect(scorePrecisionStop([], 6000, sweep)).toBe(WORST_SCORE);
    expect(scorePrecisionStop([], 6000, null)).toBe(WORST_SCORE);
  });

  it("rejects rounds the server would reject", () => {
    expect(scorePrecisionStop([100, 200], 6000, sweep)).toBeNull();
    expect(scorePrecisionStop([6001], 6000, sweep)).toBeNull();
    expect(scorePrecisionStop([-1], 6000, sweep)).toBeNull();
    expect(scorePrecisionStop([100.5], 6000, sweep)).toBeNull();
    expect(scorePrecisionStop([100], 0, sweep)).toBeNull();
    // No sweep and a real stop: nothing to replay against.
    expect(scorePrecisionStop([100], 6000, null)).toBeNull();
  });
});

describe("missDistance", () => {
  /**
   * The reason this game was built. Every other score in the catalog is bounded
   * away from zero — a tap count starts at 1, a reaction has a physiological
   * floor — so nothing exercised what a zero score does to the reveal meter or
   * the reward ladder until a perfect stop could produce one.
   */
  it("scores a perfect stop as zero", () => {
    expect(missDistance(TRACK_HALF)).toBe(0);
  });

  it("measures distance from centre in either direction", () => {
    expect(missDistance(TRACK_HALF + 12)).toBe(12);
    expect(missDistance(TRACK_HALF - 12)).toBe(12);
  });

  it("caps at the worst legal score the backend will accept", () => {
    expect(missDistance(0)).toBe(WORST_SCORE);
    expect(missDistance(TRACK_WIDTH)).toBe(WORST_SCORE);
    // Off the track entirely (or nonsense) is the worst score, never a value
    // the server's bound check would reject as fabricated.
    expect(missDistance(TRACK_WIDTH * 3)).toBe(WORST_SCORE);
    expect(missDistance(Number.NaN)).toBe(WORST_SCORE);
  });
});

describe("track geometry", () => {
  it("places the centre at the middle of the rendered track", () => {
    expect(trackPercent(TRACK_HALF)).toBe(50);
    expect(trackPercent(0)).toBe(0);
    expect(trackPercent(TRACK_WIDTH)).toBe(100);
  });

  it("never places a marker off the rendered track", () => {
    expect(trackPercent(-50)).toBe(0);
    expect(trackPercent(TRACK_WIDTH * 2)).toBe(100);
    expect(trackPercent(Number.NaN)).toBe(50);
  });

  it("sizes a target band as the share of the track it covers", () => {
    expect(zoneWidthPercent(BULLSEYE_OFF)).toBeCloseTo(5);
    expect(zoneWidthPercent(TRACK_HALF)).toBe(100);
    expect(zoneWidthPercent(-1)).toBe(0);
  });
});

describe("STOP_HOLD_MS", () => {
  /**
   * The beat exists so the player sees where they stopped, and it is paid for
   * out of an ending that already runs COMPLETE_BEAT_MS + REVEAL_DURATION_MS.
   * Long enough to read, short enough not to be the reason the ending drags.
   */
  it("is a real pause, but shorter than the celebration it precedes", () => {
    expect(STOP_HOLD_MS).toBeGreaterThan(0);
    expect(STOP_HOLD_MS).toBeLessThan(COMPLETE_BEAT_MS);
  });
});

describe("precisionVerdict", () => {
  it("reserves its best word for an exact stop", () => {
    expect(precisionVerdict(0)).toBe("precision.verdict.perfect");
    expect(precisionVerdict(BULLSEYE_OFF)).toBe("precision.verdict.deadOn");
    expect(precisionVerdict(40)).toBe("precision.verdict.wide");
  });
});
