import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  STACK_DEFAULTS,
  baseTower,
  dropBlock,
  scoreStack,
  stackBlockCentre,
  stackPeriodMs,
  stackPhysics,
  towerWidth,
  trackSpan,
} from "./stack";

/**
 * The fixture is GENERATED BY THE GO IMPLEMENTATION
 * (backend/internal/game/stack_golden_test.go) and committed. Reading it here
 * is what turns "these two simulations should agree" from a comment into a
 * failing build.
 *
 * `node:fs` in a package that may not touch the DOM or the network looks like a
 * boundary violation and is not one: this is a test file, it is never bundled
 * into an app, and a React Native client ships `stack.ts` without it. The rule
 * exists to keep the PACKAGE portable, and nothing here is part of the package.
 */
const golden = JSON.parse(
  readFileSync(
    fileURLToPath(new URL("../../../../../backend/internal/game/testdata/stack_golden.json", import.meta.url)),
    "utf8",
  ),
) as {
  durationMs: number;
  centres: { phase: number; width: number; period: number; fromLeft: boolean; centre: number }[];
  rounds: { drops: number[]; score: number }[];
};

describe("stack physics agree with the server", () => {
  // The headline guarantee. Every case the Go implementation computed must come
  // out identical here — if it does not, a player will one day watch a block
  // land on the tower and be told they missed.
  it("computes every golden block centre identically", () => {
    expect(golden.centres.length).toBeGreaterThan(0);
    const mismatches = golden.centres.filter(
      (c) => stackBlockCentre(c.phase, c.width, c.period, c.fromLeft, STACK_DEFAULTS) !== c.centre,
    );
    expect(mismatches).toEqual([]);
  });

  it("scores every golden round identically", () => {
    expect(golden.rounds.length).toBeGreaterThan(0);
    const got = golden.rounds.map((r) => scoreStack(r.drops, golden.durationMs, STACK_DEFAULTS));
    expect(got).toEqual(golden.rounds.map((r) => r.score));
  });

  // The fixture is only worth anything while the constants it was generated
  // against are the ones this side falls back to.
  it("falls back to the same constants the fixture was generated with", () => {
    expect(golden.durationMs).toBe(15000);
    expect(STACK_DEFAULTS.trackWidth).toBe(1000);
    expect(STACK_DEFAULTS.baseWidth).toBe(300);
    expect(STACK_DEFAULTS.basePeriodMs).toBe(1800);
    expect(STACK_DEFAULTS.minPeriodMs).toBe(700);
    expect(STACK_DEFAULTS.periodStepMs).toBe(90);
  });
});

describe("stackBlockCentre", () => {
  const p = STACK_DEFAULTS;
  const travel = p.trackWidth - p.baseWidth;

  it("starts at the near edge, turns at the far one, and comes back", () => {
    expect(stackBlockCentre(0, p.baseWidth, p.basePeriodMs, true, p)).toBe(p.baseWidth / 2);
    expect(stackBlockCentre(p.basePeriodMs / 2, p.baseWidth, p.basePeriodMs, true, p)).toBe(
      p.baseWidth / 2 + travel,
    );
    expect(stackBlockCentre(p.basePeriodMs, p.baseWidth, p.basePeriodMs, true, p)).toBe(p.baseWidth / 2);
  });

  // The alternation is what makes an instant re-drop useless: the next block
  // enters from the far side, nowhere near a tower that is usually mid-track.
  it("enters from the opposite edge on an alternating block", () => {
    expect(stackBlockCentre(0, p.baseWidth, p.basePeriodMs, false, p)).toBe(p.baseWidth / 2 + travel);
  });

  it("never lets the block leave the track", () => {
    for (const width of [1, 7, p.baseWidth, p.trackWidth - 1, p.trackWidth]) {
      for (let phase = 0; phase <= p.basePeriodMs * 2; phase += 7) {
        for (const fromLeft of [true, false]) {
          const centre = stackBlockCentre(phase, width, p.basePeriodMs, fromLeft, p);
          expect(centre - Math.floor(width / 2)).toBeGreaterThanOrEqual(0);
          expect(centre + Math.floor(width / 2)).toBeLessThanOrEqual(p.trackWidth);
        }
      }
    }
  });
});

describe("dropBlock", () => {
  const p = STACK_DEFAULTS;

  it("keeps the tower whole on a perfect drop", () => {
    const tower = baseTower(p);
    const { tower: next } = dropBlock(tower, p.trackWidth / 2);
    expect(next).toEqual(tower);
  });

  it("trims the overhang rather than keeping it", () => {
    const tower = baseTower(p);
    const { tower: next } = dropBlock(tower, p.trackWidth / 2 + 100);
    expect(next).not.toBeNull();
    expect(towerWidth(next!)).toBe(p.baseWidth - 100);
  });

  it("returns no tower when the block misses entirely", () => {
    const tower = baseTower(p);
    const { tower: next } = dropBlock(tower, p.baseWidth / 2);
    expect(next).toBeNull();
  });
});

describe("stackPeriodMs", () => {
  const p = STACK_DEFAULTS;

  it("ramps down one step per placed block", () => {
    expect(stackPeriodMs(0, p)).toBe(p.basePeriodMs);
    expect(stackPeriodMs(1, p)).toBe(p.basePeriodMs - p.periodStepMs);
  });

  it("floors at the minimum rather than going negative", () => {
    expect(stackPeriodMs(1000, p)).toBe(p.minPeriodMs);
  });
});

describe("scoreStack", () => {
  const p = STACK_DEFAULTS;

  it("rejects events that could not have come from a real round", () => {
    expect(scoreStack([-1], 15000, p)).toBeNull();
    expect(scoreStack([15001], 15000, p)).toBeNull();
    expect(scoreStack([900, 400], 15000, p)).toBeNull();
    expect(scoreStack([400, 400], 15000, p)).toBeNull();
    expect(scoreStack([1.5], 15000, p)).toBeNull();
  });

  // Rejection must be a property of ALL the events, not of the prefix that
  // happened to get replayed — otherwise the same dishonest payload is accepted
  // or refused according to the player's own aim. This is the case that caught
  // it on the Go side.
  it("rejects out-of-order events even when the round already ended on a miss", () => {
    expect(scoreStack([1, 900, 400], 15000, p)).toBeNull();
  });

  it("bounds how many drops a round may report", () => {
    const tooMany = Array.from({ length: p.maxDrops + 1 }, (_, i) => i + 1);
    expect(scoreStack(tooMany, 15000, p)).toBeNull();
  });
});

describe("stackPhysics", () => {
  it("falls back whole when the challenge is absent or not an object", () => {
    expect(stackPhysics(undefined)).toEqual(STACK_DEFAULTS);
    expect(stackPhysics(null)).toEqual(STACK_DEFAULTS);
    expect(stackPhysics("1000")).toEqual(STACK_DEFAULTS);
  });

  // Per field rather than all-or-nothing: a server that grows a constant this
  // build does not know about must not blank the ones it does.
  it("takes each valid field and leaves the rest at their defaults", () => {
    const p = stackPhysics({ trackWidth: 2000, baseWidth: "wide", basePeriodMs: 0, nonsense: 1 });
    expect(p.trackWidth).toBe(2000);
    expect(p.baseWidth).toBe(STACK_DEFAULTS.baseWidth);
    expect(p.basePeriodMs).toBe(STACK_DEFAULTS.basePeriodMs);
  });

  it("refuses a base wider than the track, which would freeze the block", () => {
    const p = stackPhysics({ trackWidth: 100, baseWidth: 900 });
    expect(p.baseWidth).toBeLessThanOrEqual(p.trackWidth);
  });
});

describe("trackSpan", () => {
  it("maps the tower onto percentages of the rendered track", () => {
    const p = STACK_DEFAULTS;
    expect(trackSpan(baseTower(p), p)).toEqual({ left: 35, width: 30 });
  });
});
