// The web admin's routing surface: the shared URL grammar plus the one hook
// that touches the browser. Same split as the player app — see
// @minigames/admin-core for why the grammar is a package rather than a folder.

export {
  clearedFilters,
  hasActiveFilters,
  hrefFor,
  isSafeSlug,
  isTab,
  parseAwardId,
  parseClaimStatus,
  parseGameSlug,
  parseLocation,
  parseQuery,
  parseSort,
  parseStatus,
  parseStock,
  parseTab,
  pathFor,
  resolveGameSlug,
  sameLocation,
  usesGameFilter,
  CLAIM_STATUS_VALUES,
  DEFAULT_LOCATION,
  DEFAULT_TAB,
  GAME_PARAM,
  MAX_QUERY_LENGTH,
  NEW_AWARD,
  QUERY_PARAM,
  SORT_PARAM,
  SORT_VALUES,
  STATUS_PARAM,
  STATUS_VALUES,
  STOCK_PARAM,
  STOCK_VALUES,
  TABS,
  type ClaimStatusFilter,
  type Location,
  type SortOrder,
  type StatusFilter,
  type StockFilter,
  type Tab,
} from "@minigames/admin-core";
export { useRouter, type AdminRouter, type FilterPatch } from "./useRouter";
